# Generated by Django 5.2.15 on 2026-07-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='unite',
            field=models.ForeignKey(blank=True, help_text='Unité organisationnelle de rattachement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='rh.uniteorganisationnelle', verbose_name='Unité organisationnelle'),
        ),
    ]
