# Generated by Django 5.2.15 on 2026-07-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_poste_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='nationalite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='rh.nationalite', verbose_name='Nationalité'),
        ),
    ]
