# Generated by Django 5.2.15 on 2026-07-09 12:54

import django.db.models.deletion
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_alter_agent_nationalite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinInterim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_fin_interim', models.DateField(help_text="Date effective de fin d'intérim.", verbose_name="Date de fin d'intérim")),
            ],
            options={
                'verbose_name': "Fin d'intérim",
                'verbose_name_plural': "Fins d'intérim",
                'db_table': 'rh_fin_interim',
                'ordering': ('-date_fin_interim', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Interim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_debut', models.DateField(help_text="Date de début de l'intérim.", verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin prévue.', null=True, verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Intérim',
                'verbose_name_plural': 'Intérims',
                'db_table': 'rh_interim',
                'ordering': ('-date_debut', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MiseADisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('organisme_accueil', models.CharField(help_text="Administration ou organisme d'accueil.", max_length=255, verbose_name="Organisme d'accueil")),
                ('date_debut', models.DateField(help_text='Date de début de la mise à disposition.', verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin prévue de la mise à disposition.', null=True, verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Mise à disposition',
                'verbose_name_plural': 'Mises à disposition',
                'db_table': 'rh_mise_a_disposition',
                'ordering': ('-date_debut', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PriseServiceAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_prise_service', models.DateField(help_text='Date effective de prise de service.', verbose_name='Date de prise de service')),
            ],
            options={
                'verbose_name': 'Prise de service après affectation',
                'verbose_name_plural': 'Prises de service après affectation',
                'db_table': 'rh_prise_service_affectation',
                'ordering': ('-date_prise_service', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PriseServiceInitiale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_prise_service', models.DateField(help_text='Date effective de prise de service.', verbose_name='Date de prise de service')),
            ],
            options={
                'verbose_name': 'Prise de service initiale',
                'verbose_name_plural': 'Prises de service initiales',
                'db_table': 'rh_prise_service_initiale',
                'ordering': ('-date_prise_service', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('motif', models.TextField(blank=True, default='', help_text='Motif de la radiation.', verbose_name='Motif')),
                ('observation', models.TextField(blank=True, default='', help_text='Observations complémentaires.', verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Radiation',
                'verbose_name_plural': 'Radiations',
                'db_table': 'rh_radiation',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='demission',
            options={'ordering': ('-id',), 'verbose_name': 'Démission', 'verbose_name_plural': 'Démissions'},
        ),
        migrations.AlterModelOptions(
            name='detachement',
            options={'ordering': ('-date_debut', '-id'), 'verbose_name': 'Détachement', 'verbose_name_plural': 'Détachements'},
        ),
        migrations.AlterModelOptions(
            name='disponibilite',
            options={'ordering': ('-date_debut', '-id'), 'verbose_name': 'Disponibilité', 'verbose_name_plural': 'Disponibilités'},
        ),
        migrations.AlterModelOptions(
            name='evenementcarriere',
            options={'ordering': ('-date_effet', '-id'), 'verbose_name': 'Événement de carrière', 'verbose_name_plural': 'Événements de carrière'},
        ),
        migrations.AlterModelOptions(
            name='occupationposte',
            options={'ordering': ('-date_debut', '-id'), 'verbose_name': 'Occupation de poste', 'verbose_name_plural': 'Occupations de poste'},
        ),
        migrations.AlterModelOptions(
            name='reintegration',
            options={'ordering': ('-date_reintegration', '-id'), 'verbose_name': 'Réintégration', 'verbose_name_plural': 'Réintégrations'},
        ),
        migrations.AlterModelOptions(
            name='retraite',
            options={'ordering': ('-id',), 'verbose_name': 'Retraite', 'verbose_name_plural': 'Retraites'},
        ),
        migrations.RemoveConstraint(
            model_name='detachement',
            name='ck_detachement_dates',
        ),
        migrations.RemoveConstraint(
            model_name='disponibilite',
            name='ck_disponibilite_dates',
        ),
        migrations.RemoveConstraint(
            model_name='poste',
            name='uq_poste_unite_libelle',
        ),
        migrations.RemoveIndex(
            model_name='detachement',
            name='rh_detachem_positio_1b75b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='detachement',
            name='rh_detachem_poste_i_37a8c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='detachement',
            name='rh_detachem_date_fi_51e534_idx',
        ),
        migrations.RemoveIndex(
            model_name='disponibilite',
            name='rh_disponib_positio_fa27df_idx',
        ),
        migrations.RemoveIndex(
            model_name='disponibilite',
            name='rh_disponib_date_fi_5fc03a_idx',
        ),
        migrations.RemoveIndex(
            model_name='occupationposte',
            name='rh_occupati_poste_i_c4173e_idx',
        ),
        migrations.RemoveIndex(
            model_name='reintegration',
            name='rh_reintegr_positio_2ff2d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='reintegration',
            name='rh_reintegr_structu_646ce2_idx',
        ),
        migrations.RemoveIndex(
            model_name='reintegration',
            name='rh_reintegr_poste_i_0806b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='reintegration',
            name='rh_reintegr_date_pr_fb2377_idx',
        ),
        migrations.RemoveIndex(
            model_name='retraite',
            name='rh_retraite_positio_8a7ba6_idx',
        ),
        migrations.RemoveIndex(
            model_name='retraite',
            name='rh_retraite_date_de_199811_idx',
        ),
        migrations.RemoveField(
            model_name='detachement',
            name='date_fin_prevue',
        ),
        migrations.RemoveField(
            model_name='detachement',
            name='position_administrative',
        ),
        migrations.RemoveField(
            model_name='detachement',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='disponibilite',
            name='date_fin_prevue',
        ),
        migrations.RemoveField(
            model_name='disponibilite',
            name='position_administrative',
        ),
        migrations.RemoveField(
            model_name='reintegration',
            name='date_prise_service',
        ),
        migrations.RemoveField(
            model_name='reintegration',
            name='position_administrative',
        ),
        migrations.RemoveField(
            model_name='reintegration',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='reintegration',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='reintegration',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='retraite',
            name='date_depart',
        ),
        migrations.RemoveField(
            model_name='retraite',
            name='position_administrative',
        ),
        migrations.AddField(
            model_name='detachement',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin prévue du détachement.', null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='detachement',
            name='organisme_accueil',
            field=models.CharField(blank=True, help_text="Administration ou organisme d'accueil.", max_length=255, null=True, verbose_name="Organisme d'accueil"),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin prévue.', null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='motif',
            field=models.CharField(default='', help_text='Motif de la disponibilité.', max_length=255, verbose_name='Motif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationposte',
            name='est_interim',
            field=models.BooleanField(default=False, help_text='Indique que cette occupation correspond à un intérim.', verbose_name="Occupation d'intérim"),
        ),
        migrations.AddField(
            model_name="reintegration",
            name="date_reintegration",
            field=models.DateField(
                default=datetime.date(2000, 1, 1),
                help_text="Date effective de réintégration.",
                verbose_name="Date de réintégration",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reintegration',
            name='motif',
            field=models.CharField(default='', help_text='Motif de la réintégration.', max_length=255, verbose_name='Motif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retraite',
            name='motif',
            field=models.TextField(blank=True, default='', help_text='Motif de la retraite.', verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='demission',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='demission', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AlterField(
            model_name='demission',
            name='observation',
            field=models.TextField(blank=True, default='', help_text='Observations complémentaires.', verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='detachement',
            name='date_debut',
            field=models.DateField(help_text='Date de début du détachement.', verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='detachement',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='detachement', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AlterField(
            model_name='detachement',
            name='structure',
            field=models.ForeignKey(blank=True, help_text="Structure d'accueil si elle est gérée dans le SGCP.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detachements', to='rh.structure', verbose_name="Structure d'accueil"),
        ),
        migrations.AlterField(
            model_name='detachement',
            name='unite',
            field=models.ForeignKey(blank=True, help_text="Unité organisationnelle d'accueil.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detachements', to='rh.uniteorganisationnelle', verbose_name='Unité organisationnelle'),
        ),
        migrations.AlterField(
            model_name='disponibilite',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilite', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AlterField(
            model_name='evenementcarriere',
            name='numero_acte',
            field=models.CharField(blank=True, help_text="Numéro officiel de l'acte administratif.", max_length=150, verbose_name="Numéro de l'acte"),
        ),
        migrations.AlterField(
            model_name='evenementcarriere',
            name='position_administrative',
            field=models.ForeignKey(blank=True, help_text="Position administrative résultant de l'événement lorsqu'elle est modifiée.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='rh.positionadministrative', verbose_name='Position administrative'),
        ),
        migrations.AlterField(
            model_name='occupationposte',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupations_poste', to='rh.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='occupationposte',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='occupationposte',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='occupationposte',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupations_poste', to='rh.evenementcarriere', verbose_name='Événement'),
        ),
        migrations.AlterField(
            model_name='occupationposte',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupations', to='rh.poste', verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='reintegration',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='reintegration', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AlterField(
            model_name='retraite',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='retraite', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AlterField(
            model_name='retraite',
            name='observation',
            field=models.TextField(blank=True, default='', help_text='Observations complémentaires.', verbose_name='Observation'),
        ),
        migrations.AddIndex(
            model_name='demission',
            index=models.Index(fields=['evenement'], name='rh_demissio_eveneme_cda68c_idx'),
        ),
        migrations.AddIndex(
            model_name='detachement',
            index=models.Index(fields=['evenement'], name='rh_detachem_eveneme_2d0bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='detachement',
            index=models.Index(fields=['organisme_accueil'], name='rh_detachem_organis_6862a2_idx'),
        ),
        migrations.AddIndex(
            model_name='detachement',
            index=models.Index(fields=['unite'], name='rh_detachem_unite_i_3487dd_idx'),
        ),
        migrations.AddIndex(
            model_name='detachement',
            index=models.Index(fields=['date_fin'], name='rh_detachem_date_fi_9ea40d_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilite',
            index=models.Index(fields=['evenement'], name='rh_disponib_eveneme_73ec01_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilite',
            index=models.Index(fields=['date_fin'], name='rh_disponib_date_fi_98d6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='evenementcarriere',
            index=models.Index(fields=['agent', 'date_effet'], name='rh_evenemen_agent_i_b86bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='occupationposte',
            index=models.Index(fields=['agent', 'est_interim'], name='rh_occupati_agent_i_46b6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='reintegration',
            index=models.Index(fields=['evenement'], name='rh_reintegr_eveneme_8af7db_idx'),
        ),
        migrations.AddIndex(
            model_name='reintegration',
            index=models.Index(fields=['date_reintegration'], name='rh_reintegr_date_re_9eb653_idx'),
        ),
        migrations.AddIndex(
            model_name='retraite',
            index=models.Index(fields=['evenement'], name='rh_retraite_eveneme_5f007e_idx'),
        ),
        migrations.AddConstraint(
            model_name='detachement',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='ck_detachement_dates'),
        ),
        migrations.AddConstraint(
            model_name='disponibilite',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='ck_disponibilite_dates'),
        ),
        migrations.AddConstraint(
            model_name='poste',
            constraint=models.UniqueConstraint(condition=models.Q(('unite__isnull', False)), fields=('unite', 'libelle'), name='uq_poste_unite_libelle'),
        ),
        migrations.AddConstraint(
            model_name='retraite',
            constraint=models.UniqueConstraint(fields=('evenement',), name='uq_retraite_evenement'),
        ),
        migrations.AddField(
            model_name='fininterim',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='fin_interim', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AddField(
            model_name='interim',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='interim', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AddField(
            model_name='interim',
            name='poste',
            field=models.ForeignKey(help_text='Poste assuré par intérim.', on_delete=django.db.models.deletion.PROTECT, related_name='interims', to='rh.poste', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='miseadisposition',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_disposition', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AddField(
            model_name='miseadisposition',
            name='structure',
            field=models.ForeignKey(blank=True, help_text="Structure d'accueil si elle est gérée dans le SGCP.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mises_a_disposition', to='rh.structure', verbose_name="Structure d'accueil"),
        ),
        migrations.AddField(
            model_name='miseadisposition',
            name='unite',
            field=models.ForeignKey(blank=True, help_text="Unité d'accueil si applicable.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mises_a_disposition', to='rh.uniteorganisationnelle', verbose_name='Unité organisationnelle'),
        ),
        migrations.AddField(
            model_name='priseserviceaffectation',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='prise_service_affectation', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AddField(
            model_name='priseserviceaffectation',
            name='structure',
            field=models.ForeignKey(help_text='Structure de prise de service.', on_delete=django.db.models.deletion.PROTECT, related_name='prises_service_affectation', to='rh.structure', verbose_name='Structure'),
        ),
        migrations.AddField(
            model_name='priseserviceaffectation',
            name='unite',
            field=models.ForeignKey(blank=True, help_text='Unité organisationnelle de prise de service.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prises_service_affectation', to='rh.uniteorganisationnelle', verbose_name='Unité organisationnelle'),
        ),
        migrations.AddField(
            model_name='priseserviceinitiale',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='prise_service_initiale', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AddField(
            model_name='priseserviceinitiale',
            name='structure',
            field=models.ForeignKey(help_text='Structure de prise de service.', on_delete=django.db.models.deletion.PROTECT, related_name='prises_service_initiales', to='rh.structure', verbose_name='Structure'),
        ),
        migrations.AddField(
            model_name='priseserviceinitiale',
            name='unite',
            field=models.ForeignKey(blank=True, help_text="Unité organisationnelle d'affectation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prises_service_initiales', to='rh.uniteorganisationnelle', verbose_name='Unité organisationnelle'),
        ),
        migrations.AddField(
            model_name='radiation',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.CASCADE, related_name='radiation', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AddIndex(
            model_name='fininterim',
            index=models.Index(fields=['evenement'], name='rh_fin_inte_eveneme_aeab1c_idx'),
        ),
        migrations.AddIndex(
            model_name='fininterim',
            index=models.Index(fields=['date_fin_interim'], name='rh_fin_inte_date_fi_12466b_idx'),
        ),
        migrations.AddIndex(
            model_name='interim',
            index=models.Index(fields=['evenement'], name='rh_interim_eveneme_d9388e_idx'),
        ),
        migrations.AddIndex(
            model_name='interim',
            index=models.Index(fields=['poste'], name='rh_interim_poste_i_3441c2_idx'),
        ),
        migrations.AddIndex(
            model_name='interim',
            index=models.Index(fields=['date_debut'], name='rh_interim_date_de_b17029_idx'),
        ),
        migrations.AddIndex(
            model_name='interim',
            index=models.Index(fields=['date_fin'], name='rh_interim_date_fi_da46ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='interim',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='ck_interim_dates'),
        ),
        migrations.AddIndex(
            model_name='miseadisposition',
            index=models.Index(fields=['evenement'], name='rh_mise_a_d_eveneme_1fd08d_idx'),
        ),
        migrations.AddIndex(
            model_name='miseadisposition',
            index=models.Index(fields=['organisme_accueil'], name='rh_mise_a_d_organis_f6579c_idx'),
        ),
        migrations.AddIndex(
            model_name='miseadisposition',
            index=models.Index(fields=['structure'], name='rh_mise_a_d_structu_31473b_idx'),
        ),
        migrations.AddIndex(
            model_name='miseadisposition',
            index=models.Index(fields=['unite'], name='rh_mise_a_d_unite_i_6a1bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='miseadisposition',
            index=models.Index(fields=['date_debut'], name='rh_mise_a_d_date_de_42321d_idx'),
        ),
        migrations.AddIndex(
            model_name='miseadisposition',
            index=models.Index(fields=['date_fin'], name='rh_mise_a_d_date_fi_f6cb94_idx'),
        ),
        migrations.AddConstraint(
            model_name='miseadisposition',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='ck_mise_a_disposition_dates'),
        ),
        migrations.AddIndex(
            model_name='priseserviceaffectation',
            index=models.Index(fields=['evenement'], name='rh_prise_se_eveneme_8c0624_idx'),
        ),
        migrations.AddIndex(
            model_name='priseserviceaffectation',
            index=models.Index(fields=['structure'], name='rh_prise_se_structu_9bd1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='priseserviceaffectation',
            index=models.Index(fields=['unite'], name='rh_prise_se_unite_i_e0447d_idx'),
        ),
        migrations.AddIndex(
            model_name='priseserviceaffectation',
            index=models.Index(fields=['date_prise_service'], name='rh_prise_se_date_pr_9e5607_idx'),
        ),
        migrations.AddConstraint(
            model_name='priseserviceaffectation',
            constraint=models.UniqueConstraint(fields=('evenement',), name='uq_ps_affectation_evenement'),
        ),
        migrations.AddIndex(
            model_name='priseserviceinitiale',
            index=models.Index(fields=['evenement'], name='rh_prise_se_eveneme_98f653_idx'),
        ),
        migrations.AddIndex(
            model_name='priseserviceinitiale',
            index=models.Index(fields=['structure'], name='rh_prise_se_structu_39dec7_idx'),
        ),
        migrations.AddIndex(
            model_name='priseserviceinitiale',
            index=models.Index(fields=['unite'], name='rh_prise_se_unite_i_e7da13_idx'),
        ),
        migrations.AddIndex(
            model_name='priseserviceinitiale',
            index=models.Index(fields=['date_prise_service'], name='rh_prise_se_date_pr_a8678f_idx'),
        ),
        migrations.AddConstraint(
            model_name='priseserviceinitiale',
            constraint=models.UniqueConstraint(fields=('evenement',), name='uq_prise_service_initiale_evenement'),
        ),
        migrations.AddIndex(
            model_name='radiation',
            index=models.Index(fields=['evenement'], name='rh_radiatio_eveneme_56fe47_idx'),
        ),
        migrations.AddConstraint(
            model_name='radiation',
            constraint=models.UniqueConstraint(fields=('evenement',), name='uq_radiation_evenement'),
        ),
    ]
