# Generated by Django 5.2.15 on 2026-07-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_fininterim_interim_miseadisposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='evenement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='affectation', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='corps',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='echelon',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='etatcivil',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='hierarchie',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='nationalite',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='niveaucompetence',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='niveauformation',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='organismeformation',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='positionadministrative',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='sexe',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='sourcefinancement',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='statutagent',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='statutevenement',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typeabsence',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typecompetence',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typeconge',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typedecoration',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typedocumentmedical',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typeevenement',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typeformation',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typemission',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typesanction',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typestructure',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typeuniteorganisationnelle',
            name='code',
            field=models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code'),
        ),
    ]
