# Generated by Django 5.2.15 on 2026-07-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_alter_affectation_evenement_alter_classe_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='est_courante',
            field=models.BooleanField(default=False, verbose_name='Affectation courante'),
        ),
    ]
