# Generated by Django 5.2.15 on 2026-07-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_alter_affectation_est_courante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclassement',
            name='corps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclassements', to='rh.corps', verbose_name='Nouveau corps'),
        ),
        migrations.AlterField(
            model_name='reclassement',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclassements', to='rh.classe', verbose_name='Nouvelle classe'),
        ),
        migrations.AlterField(
            model_name='reclassement',
            name='echelon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclassements', to='rh.echelon', verbose_name='Nouvel échelon'),
        ),
        migrations.AlterField(
            model_name='reclassement',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclassements', to='rh.grade', verbose_name='Nouveau grade'),
        ),
    ]
