# Generated by Django 5.2.15 on 2026-07-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_reclassement_corps_alter_reclassement_classe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='radiation',
            name='uq_radiation_evenement',
        ),
        migrations.RemoveConstraint(
            model_name='retraite',
            name='uq_retraite_evenement',
        ),
        migrations.AlterField(
            model_name='demission',
            name='observation',
            field=models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='observation',
            field=models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='retraite',
            name='observation',
            field=models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation'),
        ),
    ]
