# Generated by Django 5.2.15 on 2026-07-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_remove_radiation_uq_radiation_evenement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decisionconge',
            options={'ordering': ('-evenement__date_effet', 'type_conge__libelle'), 'verbose_name': 'Décision de congé', 'verbose_name_plural': 'Décisions de congé'},
        ),
        migrations.AlterField(
            model_name='decisionconge',
            name='evenement',
            field=models.OneToOneField(help_text='Événement de carrière associé à cette décision.', on_delete=django.db.models.deletion.CASCADE, related_name='decision_conge', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
        migrations.CreateModel(
            name='TypeMouvementConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('code', models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(help_text='Libellé du référentiel.', max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, default='', help_text='Description du référentiel.', verbose_name='Description')),
                ('sens', models.SmallIntegerField(choices=[(1, 'Crédit'), (-1, 'Débit')], help_text='Sens du mouvement sur le compteur de congé.', verbose_name='Sens')),
            ],
            options={
                'verbose_name': 'Type de mouvement de congé',
                'verbose_name_plural': 'Types de mouvements de congé',
                'db_table': 'rh_type_mouvement_conge',
                'ordering': ('libelle',),
                'indexes': [models.Index(fields=['code'], name='rh_type_mou_code_e98d6e_idx'), models.Index(fields=['libelle'], name='rh_type_mou_libelle_9c0a8b_idx'), models.Index(fields=['sens'], name='rh_type_mou_sens_547123_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sens__in', (-1, 1))), name='ck_type_mouvement_conge_sens')],
            },
        ),
    ]
