# Generated by Django 5.2.15 on 2026-07-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_alter_decisionconge_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('decision_conge', models.OneToOneField(help_text='Décision de congé ouvrant le droit.', on_delete=django.db.models.deletion.CASCADE, related_name='compteur', to='rh.decisionconge', verbose_name='Décision de congé')),
            ],
            options={
                'verbose_name': 'Compteur de congé',
                'verbose_name_plural': 'Compteurs de congé',
                'db_table': 'rh_compteur_conge',
            },
        ),
        migrations.CreateModel(
            name='MouvementCompteurConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('nombre_jours', models.PositiveSmallIntegerField(help_text='Nombre de jours concernés par le mouvement.', verbose_name='Nombre de jours')),
                ('date_mouvement', models.DateField(help_text="Date d'effet du mouvement.", verbose_name='Date du mouvement')),
                ('observation', models.TextField(blank=True, help_text='Observation éventuelle.', null=True, verbose_name='Observation')),
                ('compteur', models.ForeignKey(help_text='Compteur concerné.', on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='rh.compteurconge', verbose_name='Compteur de congé')),
                ('type_mouvement', models.ForeignKey(help_text='Nature du mouvement.', on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='rh.typemouvementconge', verbose_name='Type de mouvement')),
            ],
            options={
                'verbose_name': 'Mouvement de compteur de congé',
                'verbose_name_plural': 'Mouvements de compteur de congé',
                'db_table': 'rh_mouvement_compteur_conge',
                'ordering': ('-date_mouvement', '-id'),
                'indexes': [models.Index(fields=['compteur'], name='rh_mouvemen_compteu_80e06d_idx'), models.Index(fields=['type_mouvement'], name='rh_mouvemen_type_mo_b69ade_idx'), models.Index(fields=['date_mouvement'], name='rh_mouvemen_date_mo_6b4df7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nombre_jours__gt', 0)), name='ck_mouvement_compteur_conge_nombre_jours')],
            },
        ),
    ]
