# Generated by Django 5.2.15 on 2026-07-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_compteurconge_mouvementcompteurconge'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeabsence',
            name='deduire_conge',
            field=models.BooleanField(default=False, help_text='Indique si cette absence doit être déduite du reliquat de congé.', verbose_name='Déduire du congé'),
        ),
    ]
