# Generated by Django 5.2.15 on 2026-07-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_typeabsence_deduire_conge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeabsence',
            name='deduire_conge',
        ),
    ]
