# Generated by Django 5.2.15 on 2026-07-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_remove_typeabsence_deduire_conge'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='jours_deductibles',
            field=models.PositiveSmallIntegerField(default=0, help_text="Nombre de jours imputables sur le compteur de congé conformément à l'autorisation d'absence.", verbose_name='Jours déductibles'),
        ),
    ]
