# Generated by Django 5.2.15 on 2026-07-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_absence_jours_deductibles'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentagent',
            name='idx_docagt_structure',
        ),
        migrations.RemoveField(
            model_name='documentagent',
            name='structure',
        ),
    ]
