# Generated by Django 5.2.15 on 2026-07-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_remove_documentagent_idx_docagt_structure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutation',
            options={'ordering': ['-id'], 'verbose_name': 'Mutation', 'verbose_name_plural': 'Mutations'},
        ),
        migrations.RemoveIndex(
            model_name='mutation',
            name='rh_mutation_date_pr_d11c66_idx',
        ),
        migrations.RemoveField(
            model_name='mutation',
            name='date_prise_service',
        ),
    ]
