# Generated by Django 5.2.15 on 2026-07-20 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0015_alter_mutation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenementcarriere",
            name="statut",
        ),

        migrations.AddField(
            model_name="evenementcarriere",
            name="statut",
            field=models.ForeignKey(
                to="rh.statutagent",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evenements",
                verbose_name="Statut",
                help_text="Statut courant de l'agent.",
                default=10,
            ),
            preserve_default=False,
        ),
    ]