# Generated by Django 5.2.15 on 2026-07-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0016_alter_evenementcarriere_statut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenementcarriere",
            name="statut",
        ),

        migrations.AddField(
            model_name="evenementcarriere",
            name="statut",
            field=models.ForeignKey(
                to="rh.statutevenement",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evenements",
                verbose_name="Statut",
                help_text="Statut courant de l'événement.",
                default=2,   # EN_ATTENTE
            ),
            preserve_default=False,
        ),
    ]