# Generated by Django 5.2.15 on 2026-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_alter_evenementcarriere_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenementcarriere',
            options={'ordering': ('-created_at',), 'verbose_name': 'Événement de carrière', 'verbose_name_plural': 'Événements de carrière'},
        ),
        migrations.AlterModelOptions(
            name='recrutement',
            options={'ordering': ['-date_recrutement', '-id'], 'verbose_name': 'Recrutement', 'verbose_name_plural': 'Recrutements'},
        ),
        migrations.RemoveIndex(
            model_name='recrutement',
            name='rh_recrutem_date_pr_055c5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='recrutement',
            name='rh_recrutem_poste_i_0565cc_idx',
        ),
        migrations.RemoveField(
            model_name='recrutement',
            name='date_anciennete',
        ),
        migrations.RemoveField(
            model_name='recrutement',
            name='date_prise_service',
        ),
        migrations.RemoveField(
            model_name='recrutement',
            name='position_administrative',
        ),
        migrations.RemoveField(
            model_name='recrutement',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='recrutement',
            name='unite',
        ),
        migrations.AddField(
            model_name='recrutement',
            name='date_recrutement',
            field=models.DateField(default='2026-01-23', help_text='Date effective du recrutement dans la fonction publique.', verbose_name='Date de recrutement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recrutement',
            name='numero_document',
            field=models.CharField(blank=True, help_text='Numéro officiel du document.', max_length=150, verbose_name='Numéro du document'),
        ),
        migrations.AddIndex(
            model_name='recrutement',
            index=models.Index(fields=['date_recrutement'], name='rh_recrutem_date_re_3a3e7f_idx'),
        ),
    ]
