# Generated by Django 5.2.15 on 2026-07-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_alter_evenementcarriere_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation',
            options={'verbose_name': 'Affectation', 'verbose_name_plural': 'Affectations'},
        ),
        migrations.RemoveConstraint(
            model_name='affectation',
            name='ck_affectation_dates',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='date_prise_service',
        ),
        migrations.AlterField(
            model_name='affectation',
            name='evenement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affectation', to='rh.evenementcarriere', verbose_name='Événement de carrière'),
        ),
    ]
