# Generated by Django 5.2.15 on 2026-07-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_alter_affectation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Structure de rattachement dans l'organisation administrative.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='rh.structure', verbose_name='Structure parente'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['parent'], name='rh_structur_parent__a88480_idx'),
        ),
    ]
