# Generated by Django 5.2.15 on 2026-07-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_structure_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='rh.uniteorganisationnelle', verbose_name='Unité organisationnelle'),
        ),
    ]
