# Generated by Django 5.2.15 on 2026-07-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0021_alter_affectation_unite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomination',
            options={'ordering': ['-id'], 'verbose_name': 'Nomination', 'verbose_name_plural': 'Nominations'},
        ),
        migrations.RemoveIndex(
            model_name='nomination',
            name='rh_nominati_date_pr_c56063_idx',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='date_prise_service',
        ),
    ]
