# Generated by Django 5.2.15 on 2026-07-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_alter_nomination_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interim',
            options={'ordering': ('-id',), 'verbose_name': 'Intérim', 'verbose_name_plural': 'Intérims'},
        ),
        migrations.RemoveConstraint(
            model_name='interim',
            name='ck_interim_dates',
        ),
        migrations.RemoveIndex(
            model_name='interim',
            name='rh_interim_date_de_b17029_idx',
        ),
        migrations.RemoveIndex(
            model_name='interim',
            name='rh_interim_date_fi_da46ea_idx',
        ),
        migrations.RemoveField(
            model_name='interim',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='interim',
            name='date_fin',
        ),
    ]
