# Generated by Django 5.2.15 on 2026-07-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_alter_interim_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInaptitudeMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('code', models.CharField(help_text='Code unique du référentiel.', max_length=30, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(help_text='Libellé du référentiel.', max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, default='', help_text='Description du référentiel.', verbose_name='Description')),
            ],
            options={
                'verbose_name': "Type d'inaptitude médicale",
                'verbose_name_plural': "Types d'inaptitude médicale",
                'db_table': 'rh_type_inaptitude_medicale',
                'ordering': ['libelle'],
                'indexes': [models.Index(fields=['code'], name='rh_type_ina_code_9d41fa_idx'), models.Index(fields=['libelle'], name='rh_type_ina_libelle_14e561_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccidentTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_accident', models.DateField(help_text="Date de survenance de l'accident.", verbose_name="Date de l'accident")),
                ('lieu_accident', models.CharField(max_length=255, verbose_name="Lieu de l'accident")),
                ('circonstances', models.TextField(help_text="Description succincte des circonstances de l'accident.", verbose_name='Circonstances')),
                ('consequences', models.TextField(blank=True, default='', help_text='Conséquences administratives constatées.', verbose_name='Conséquences')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('evenement', models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='rh.evenementcarriere', verbose_name='Événement de carrière')),
            ],
            options={
                'verbose_name': 'Accident de travail',
                'verbose_name_plural': 'Accidents de travail',
                'db_table': 'rh_accident_travail',
                'ordering': ('-date_accident',),
                'indexes': [models.Index(fields=['date_accident'], name='rh_accident_date_ac_cf6234_idx')],
            },
        ),
        migrations.CreateModel(
            name='CongeMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('debut_conge', models.DateField(help_text='Date de début du congé de maladie.', verbose_name='Début du congé')),
                ('fin_conge', models.DateField(help_text='Date de fin du congé de maladie.', verbose_name='Fin du congé')),
                ('evenement', models.OneToOneField(help_text='Événement de carrière associé au congé de maladie.', on_delete=django.db.models.deletion.PROTECT, related_name='conge_maladie', to='rh.evenementcarriere', verbose_name='Événement de carrière')),
            ],
            options={
                'verbose_name': 'Congé de maladie',
                'verbose_name_plural': 'Congés de maladie',
                'db_table': 'rh_conge_maladie',
                'ordering': ['-debut_conge', '-id'],
                'indexes': [models.Index(fields=['evenement'], name='rh_conge_ma_eveneme_c68298_idx'), models.Index(fields=['debut_conge'], name='rh_conge_ma_debut_c_fc33ec_idx'), models.Index(fields=['fin_conge'], name='rh_conge_ma_fin_con_879096_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin_conge__gte', models.F('debut_conge'))), name='ck_conge_maladie_dates')],
            },
        ),
        migrations.CreateModel(
            name='CongeMaternite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_debut', models.DateField(help_text='Premier jour du congé de maternité.', verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Dernier jour du congé de maternité.', verbose_name='Date de fin')),
                ('evenement', models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='rh.evenementcarriere', verbose_name='Événement de carrière')),
            ],
            options={
                'verbose_name': 'Congé de maternité',
                'verbose_name_plural': 'Congés de maternité',
                'db_table': 'rh_conge_maternite',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['date_debut'], name='rh_conge_ma_date_de_2eccef_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='ck_conge_maternite_dates_coherentes')],
            },
        ),
        migrations.CreateModel(
            name='RepriseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_reprise', models.DateField(help_text='Date effective de reprise des fonctions.', verbose_name='Date de reprise')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('evenement', models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='rh.evenementcarriere', verbose_name='Événement de carrière')),
            ],
            options={
                'verbose_name': 'Reprise de service',
                'verbose_name_plural': 'Reprises de service',
                'db_table': 'rh_reprise_service',
                'ordering': ('-date_reprise',),
                'indexes': [models.Index(fields=['date_reprise'], name='rh_reprise__date_re_d5507b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestrictionMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_effet', models.DateField(help_text="Date de prise d'effet de la restriction.", verbose_name="Date d'effet")),
                ('date_fin', models.DateField(blank=True, help_text="Date de fin de la restriction lorsqu'elle est temporaire.", null=True, verbose_name='Date de fin')),
                ('restriction', models.TextField(help_text="Description de la restriction administrative imposée à l'agent.", verbose_name='Restriction')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('evenement', models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='rh.evenementcarriere', verbose_name='Événement de carrière')),
            ],
            options={
                'verbose_name': 'Restriction médicale',
                'verbose_name_plural': 'Restrictions médicales',
                'db_table': 'rh_restriction_medicale',
                'ordering': ('-date_effet',),
                'indexes': [models.Index(fields=['date_effet'], name='rh_restrict_date_ef_f34ce4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_effet')), _connector='OR'), name='ck_restriction_medicale_dates')],
            },
        ),
        migrations.CreateModel(
            name='InaptitudeMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('date_effet', models.DateField(help_text="Date de prise d'effet de la décision d'inaptitude.", verbose_name="Date d'effet")),
                ('date_fin', models.DateField(blank=True, help_text="Date de fin de l'inaptitude lorsqu'elle est temporaire.", null=True, verbose_name='Date de fin')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('evenement', models.OneToOneField(help_text='Événement de carrière associé.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='rh.evenementcarriere', verbose_name='Événement de carrière')),
                ('type_inaptitude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inaptitudes_medicales', to='rh.typeinaptitudemedicale', verbose_name="Type d'inaptitude")),
            ],
            options={
                'verbose_name': 'Inaptitude médicale',
                'verbose_name_plural': 'Inaptitudes médicales',
                'db_table': 'rh_inaptitude_medicale',
                'ordering': ('-date_effet',),
                'indexes': [models.Index(fields=['type_inaptitude'], name='rh_inaptitu_type_in_b98dc6_idx'), models.Index(fields=['date_effet'], name='rh_inaptitu_date_ef_7b1a45_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_effet')), _connector='OR'), name='ck_inaptitude_medicale_dates')],
            },
        ),
    ]
