# Generated by Django 5.2.15 on 2026-08-03 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_typeinaptitudemedicale_accidenttravail_congemaladie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='structure_racine',
            field=models.ForeignKey(blank=True, help_text="Structure racine propriétaire du dossier de l'agent.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='rh.structure', verbose_name='Structure racine'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Compte utilisateur associé à l'agent.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['structure_racine'], name='rh_agent_structu_fb2227_idx'),
        ),
    ]
