# Generated by Django 5.2.15 on 2026-08-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0025_agent_structure_racine_agent_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement.", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de la dernière modification.', verbose_name='Date de modification')),
                ('observation', models.TextField(blank=True, default='', help_text='Observation libre.', verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'enregistrement est actif.", verbose_name='Actif')),
                ('structure_racine', models.ForeignKey(blank=True, help_text='Structure Racine administrée par cet utilisateur.', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrateurs', to='rh.structure', verbose_name='Structure racine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_administration', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Profil d'administration",
                'verbose_name_plural': "Profils d'administration",
                'db_table': 'adm_profil_administration',
            },
        ),
    ]
